import { StyleSheet, Platform } from "react-native";

import { Fonts, Colors, Metrics } from "@theme";

export default StyleSheet.create({
  inputContainerLight: {
    // paddingBottom: Platform.OS === 'ios' ? Metrics.ratio(18) : Metrics.ratio(8),
    // padding: Metrics.ratio(8),
    fontSize: Metrics.ratio(14),
    // textAlignVertical: 'top',
    // color: Colors.lightModeTextInput.backgroundColor,
    fontFamily: Fonts.type.medium,
    flex: 1,
  },
  inputContainerDark: {
    // paddingBottom: Platform.OS === 'ios' ? Metrics.ratio(18) : Metrics.ratio(8),
    // padding: Metrics.ratio(8),
    fontSize: Metrics.ratio(14),
    // textAlignVertical: 'top',
    color: Colors.lightModeTextInput.backgroundColor,
    fontFamily: Fonts.type.medium,
    flex: 1,
  },
  multline: {
    height: Metrics.multilineHeight,
    paddingBottom: Metrics.smallMargin,
    paddingTop: Platform.select({ ios: Metrics.smallMargin }),
  },
  inputContainer: {
    // flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    height: Metrics.ratio(50),
    width: "100%",
    paddingHorizontal: Metrics.ratio(10),
    // marginTop: Metrics.ratio(12),
    borderRadius: Metrics.ratio(16),
    borderWidth: 1,
    borderBottomColor: Colors.lightModeTextInput.borderColor,
    borderTopColor: Colors.lightModeTextInput.borderColor,
    borderRightColor: Colors.lightModeTextInput.borderColor,
    borderLeftColor: Colors.lightModeTextInput.borderColor,
    backgroundColor: "transparent",
  },
  inputContainerInActive: {
    // flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    height: Metrics.ratio(50),
    width: "100%",
    paddingHorizontal: Metrics.ratio(10),
    // marginTop: Metrics.ratio(12),
    borderRadius: Metrics.ratio(16),
    borderWidth: 1,
    borderBottomColor: Colors.lightModeTextInput.borderColor,
    borderTopColor: Colors.lightModeTextInput.borderColor,
    borderRightColor: Colors.lightModeTextInput.borderColor,
    borderLeftColor: Colors.lightModeTextInput.borderColor,
    backgroundColor: "transparent",
  },
  title: {
    lineHeight: Metrics.ratio(16),
    marginTop: Metrics.ratio(20),
    fontSize: Metrics.ratio(13),
    fontFamily: Fonts.type.regular,
    color: Colors.TextPrimary,
  },
  leftInputStyles: {
    paddingRight: Metrics.ratio(10),
  },
  errorText: {
    fontFamily: Fonts.type.light,
    fontSize: Metrics.ratio(12),
    color: Colors.lightModeTextInput.errorColor,
    marginTop: Metrics.ratio(2),
  },
  hint: {
    marginTop: Metrics.ratio(6),
  },
  arrowStyle: { marginRight: Metrics.ratio(15) },
  bottomSpace: { marginBottom: Metrics.ratio(10) },
  topSpace: { marginTop: Metrics.ratio(6) },
});
